name: Node CI

on: [push, pull_request]

jobs:
    build:
        strategy:
            matrix:
                platform: [ubuntu-latest, windows-latest]
                node-version:
                    - 16.x
                    - 14.x
                    - 12.x
        runs-on: ${{ matrix.platform }}

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            # Pulling caches itself it expensive. Which one is faster?
            #    - name: Get yarn cache
            #      id: yarn-cache
            #      run: echo "::set-output name=dir::$(yarn cache dir)"
            #    - uses: actions/cache@v1
            #      with:
            #        path: ${{ steps.yarn-cache.outputs.dir }}
            #        key: ${{ runner.os }}-yarn-${{ hashFiles('package.json') }}
            #        restore-keys: |
            #          ${{ runner.os }}-yarn-

            - name: yarn install, lint, and test
              run: |
                  yarn install --ignore-scripts
                  yarn prepublishOnly
              env:
                  CI: true
